# Generated by Django 5.2.6 on 2025-11-21 13:05

import digits.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_number', models.CharField(max_length=5)),
                ('random_number', models.CharField(max_length=5)),
                ('security_string', models.CharField(default=digits.models.make_security_string, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revealed', models.BooleanField(default=False)),
                ('challenge_indices', models.CharField(blank=True, max_length=32)),
                ('challenge_created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
