# Generated by Django 5.2.6 on 2025-11-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='security_string',
            field=models.CharField(default='abcdefghijklmnopqrst', max_length=20),
        ),
    ]
