# Generated by Django 5.2.6 on 2025-11-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digits', '0002_alter_entry_security_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='security_string',
            field=models.CharField(default='abcdefghijklmnopqrstabcdefghijklmnopqrst', max_length=20),
        ),
    ]
