# Generated by Django 5.2.6 on 2025-12-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digits', '0004_alter_entry_security_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='security_string',
            field=models.CharField(default='heivow6295ke03HWPTCKEne9375me05gebtFW0TN', max_length=40),
        ),
    ]
